[package]
name = "checkspam"
version = "0.1.0"
edition = "2024"

[dependencies]
google-gmail1 = "5.0.4+20230221"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = "0.24"
tokio = { version = "1", features = ["full"] }
yup-oauth2 = { version = "^8.0.0", default-features = false, features = ["hyper-rustls"] } # Ensure this version aligns with google-gmail1

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"
anyhow = "1.0"
backoff = { version = "0.4", features = ["tokio"] }
open = "5.0" # Check for latest version
futures = "0.3" # For stream processing and join_all
async-recursion = "1.0" # If needed for recursive async functions, e.g. pagination
url = "2.3" # For parsing URLs if needed for auth callback manually
hex = "0.4" # yup-oauth2 might need it for some token operations if not a direct dep

[patch.crates-io]
# Potentially needed if yup-oauth2 has ring dependency issues on some platforms
# ring = { git = "https://github.com/briansmith/ring", rev = "..." }
